"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from .database_config import build_database_config
from .environment import load_private_environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_private_environment(BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('BIOCLEAN_SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('BIOCLEAN_ENV', 'dev') == 'prod':
        raise ImproperlyConfigured('BIOCLEAN_SECRET_KEY must be set in production.')
    SECRET_KEY = 'django-insecure-local-development-only'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "172.23.0.199",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'api',
    'organizations',
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'organizations.middleware.OrganizationDatabaseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'frontend' / 'dist'],  # React index.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': build_database_config('BIOCLEAN_DATABASE', BASE_DIR / 'db.sqlite3'),
    'platform': build_database_config(
        'BIOCLEAN_PLATFORM_DATABASE',
        BASE_DIR / 'platform.sqlite3',
    ),
}

PLATFORM_DATABASE_ALIAS = 'platform'
MULTI_TENANT_ENABLED = os.getenv('BIOCLEAN_MULTI_TENANT', '0') == '1'
DATABASE_ROUTERS = ['organizations.db_router.OrganizationDatabaseRouter']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# In SaaS mode the organization middleware validates each hostname against the
# central registry. It must run before Django rejects a new organization domain.
if MULTI_TENANT_ENABLED:
    ALLOWED_HOSTS = ['*']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# ---------------- STATIC ----------------

STATIC_URL = '/static/'

# Откуда брать статические файлы (React build)
STATICFILES_DIRS = [
    BASE_DIR / 'frontend' / 'dist',
]

# Куда собирать collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------------- CORS ----------------

CORS_ALLOW_ALL_ORIGINS = True

# ---------------- DEFAULT PK ----------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
