# Generated by Django 5.2.8 on 2025-12-08 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('top', 'Верхняя одежда (имеет размер)'), ('shoes', 'Обувь (имеет размер)'), ('other', 'Безразмерная экипировка')], max_length=20, verbose_name='Тип одежды')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothesStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='Размер обязателен для верхней одежды и обуви', max_length=20, null=True, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('date_income', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.clothesitem', verbose_name='Вид одежды')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('clothes_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер одежды')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Рост')),
                ('shoe_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер обуви')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.department', verbose_name='Подразделение')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.position', verbose_name='Должность')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service', verbose_name='Служба')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('size', models.CharField(blank=True, help_text='Для верхней одежды и обуви', max_length=20, null=True, verbose_name='Размер')),
                ('operation_life_months', models.PositiveIntegerField(default=12, verbose_name='Срок эксплуатации (в месяцах)')),
                ('order_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт приказа')),
                ('date_received', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('date_expire', models.DateField(blank=True, null=True, verbose_name='Дата окончания срока носки')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clothesitem', verbose_name='Экипировка')),
                ('stock_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.clothesstockbatch', verbose_name='Партия со склада')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
