# Generated by Django 5.2.8 on 2025-12-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='clothes_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер одежды'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shoe_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер обуви'),
        ),
    ]
