# Generated by Django 6.0.1 on 2026-01-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_clothes_size_alter_employee_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesissue',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='Для верхней одежды и обуви', null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='clothesitem',
            name='type',
            field=models.CharField(choices=[('top', 'Верхняя одежда'), ('shoes', 'Обувь'), ('other', 'Безразмерная экипировка')], max_length=20, verbose_name='Тип одежды'),
        ),
    ]
