# Generated by Django 6.0.1 on 2026-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_clothesissue_size_alter_clothesitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesstockbatch',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='Размер обязателен для верхней одежды и обуви', null=True, verbose_name='Размер'),
        ),
    ]
