# Generated by Django 6.0.1 on 2026-01-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_clothesstockbatch_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothesissue',
            options={'ordering': ['-date_received'], 'verbose_name': 'Выдача одежды', 'verbose_name_plural': 'Выдачи одежды'},
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='stock_batch',
        ),
        migrations.AlterField(
            model_name='clothesissue',
            name='size',
            field=models.PositiveIntegerField(blank=True, help_text='Обязателен для верхней одежды и обуви', null=True, verbose_name='Размер'),
        ),
    ]
