# Generated by Django 6.0.1 on 2026-01-30 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_clothesissue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothesissue',
            options={'ordering': ['-date_received']},
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='date_expire',
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='item',
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='operation_life_months',
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='order_point',
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='clothesissue',
            name='size',
        ),
        migrations.AlterField(
            model_name='clothesissue',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='clothesissue',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Общее примечание'),
        ),
        migrations.CreateModel(
            name='ClothesIssueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер')),
                ('operation_life_months', models.PositiveIntegerField(default=12, verbose_name='Срок эксплуатации (мес.)')),
                ('order_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пункт приказа')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('date_expire', models.DateField(blank=True, null=True, verbose_name='Дата окончания носки')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.clothesissue', verbose_name='Выдача')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clothesitem', verbose_name='Экипировка')),
            ],
        ),
    ]
