# Generated by Django 6.0.1 on 2026-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clothesissue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesissueitem',
            name='order_point',
        ),
    ]
