# Generated by Django 5.2.8 on 2026-02-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_clothesissueitem_order_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothesissueitem',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clothesstockbatch',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Указывается только для верхней одежды', null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='clothesissueitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clothesitem', verbose_name='Наименование'),
        ),
    ]
