# Generated by Django 6.0.1 on 2026-02-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_clothesissueitem_height_clothesstockbatch_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothesitem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование'),
        ),
    ]
