# Generated by Django 6.0.1 on 2026-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_clothesitem_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'middle_name', 'department', 'service', 'position'), name='unique_employee_full_identity'),
        ),
    ]
