# Generated by Django 6.0.1 on 2026-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employee_unique_employee_full_identity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterConstraint(
            model_name='employee',
            name='unique_employee_full_identity',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'middle_name', 'department', 'service', 'position'), name='unique_employee_full_identity', violation_error_message='Сотрудник с такими ФИО, подразделением, службой и должностью уже существует'),
        ),
    ]
