# Generated by Django 6.0.1 on 2026-02-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_date_income_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothesstockbatch',
            name='date_income',
        ),
    ]
