# Generated by Django 6.0.1 on 2026-02-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='item_type',
        ),
    ]
