# Generated by Django 6.0.1 on 2026-02-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_stock_item_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClothesStockBatch',
        ),
    ]
