# Generated by Django 5.2.8 on 2026-09-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_clothesstockbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Норма выдачи',
                'verbose_name_plural': 'Нормы выдачи',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='issue_norm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='api.issuenorm', verbose_name='Норма выдачи'),
        ),
        migrations.CreateModel(
            name='IssueNormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('operation_life_months', models.PositiveIntegerField(default=12, verbose_name='Срок эксплуатации (мес.)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='norm_items', to='api.clothesitem', verbose_name='СИЗ')),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.issuenorm', verbose_name='Норма')),
            ],
            options={
                'verbose_name': 'Позиция нормы выдачи',
                'verbose_name_plural': 'Позиции норм выдачи',
                'ordering': ['item__name'],
                'constraints': [models.UniqueConstraint(fields=('norm', 'item'), name='unique_item_in_issue_norm', violation_error_message='Это СИЗ уже добавлено в норму')],
            },
        ),
    ]
