# Generated by Django 6.0.1 on 2026-08-26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Наименование")),
                ("slug", models.CharField(help_text="Используется в адресе организации и имени ее базы данных.", max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message="Код организации может содержать только латинские строчные буквы, цифры и дефисы.", regex="^[a-z0-9-]+$")], verbose_name="Код организации")),
                ("database_name", models.CharField(max_length=63, unique=True, verbose_name="Имя рабочей базы")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(max_length=255, unique=True, verbose_name="Домен")),
                ("is_primary", models.BooleanField(default=False, verbose_name="Основной")),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="domains", to="organizations.organization", verbose_name="Организация")),
            ],
            options={
                "verbose_name": "Домен организации",
                "verbose_name_plural": "Домены организаций",
                "ordering": ["domain"],
            },
        ),
    ]
